version: '3.8'

# x-common-variables: &common-variables

services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'

  api:
    build:
      dockerfile: Dockerfile
      context: './server'
    # depends_on:
    #   - mysql_db
    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
